// <auto-generated />
using System;
using LojaDeFunkos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaDeFunkos.Data.Migrations
{
    [DbContext(typeof(FunkoDbContext))]
    [Migration("20231205234125_AdicionarDadosIniciaisFunko")]
    partial class AdicionarDadosIniciaisFunko
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("LojaDeFunkos.Models.Funko", b =>
                {
                    b.Property<int>("FunkoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("FunkoId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Funko");
                });

            modelBuilder.Entity("LojaDeFunkos.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("LojaDeFunkos.Models.Funko", b =>
                {
                    b.HasOne("LojaDeFunkos.Models.Marca", null)
                        .WithMany("Funkos")
                        .HasForeignKey("MarcaId");
                });

            modelBuilder.Entity("LojaDeFunkos.Models.Marca", b =>
                {
                    b.Navigation("Funkos");
                });
#pragma warning restore 612, 618
        }
    }
}
