// <auto-generated />
using LojaDeFunkos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaDeFunkos.Data.Migrations
{
    [DbContext(typeof(FunkoDbContext))]
    partial class FunkoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");
#pragma warning restore 612, 618
        }
    }
}
